language: node_js
node_js:
  - 10
before_install:
  - curl -L https://unpkg.com/@pnpm/self-installer | node
  - pnpm config set store-dir ~/.pnpm-store
install:
  - pnpm install --force
cache:
  npm: false
  directories:
    - "~/.pnpm-store"